<div class="panel panel-default">
	<div class="panel-heading">About Luga Router</div>
	<div class="panel-body">

		<p>
			TODO
		</p>

	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">Unit tests</div>
	<div class="panel-body">
		<p>
			Luga Router contains a comprehensive set of <a href="../test/SpecRunner.htm">unit tests</a>, developed
			with <a href="https://github.com/jasmine/jasmine">Jasmine</a>
		</p>

		<p>
			The unit tests play a fundamental role in ensuring the code is robust and, at the very same time,
			provide plenty of useful information about the API
		</p>

		<p>
			Code coverage is usually around 100%. You can check <a
				href="../test/coverage/lcov-report/src/index.html">coverage report</a> by yourself
		</p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">Dependencies and compatibility</div>
	<div class="panel-body">
		<p>
			TODO
		</p>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">License</div>
	<div class="panel-body">
		<p>Luga Router is distributed under the <a href="http://www.apache.org/licenses/LICENSE-2.0.html">Apache
			2.0</a> license</p>

		<p>
			The Apache License requires preservation of the copyright notice and disclaimer.
			The Apache License allows the user of the software the freedom to use the software for any purpose,
			to distribute it, to modify it, and to distribute modified versions of the software
		</p>
	</div>
</div>