<div class="panel panel-default">
	<div class="panel-heading luga-docs-api-heading">luga.Router.setup(options)</div>
	<div class="panel-body">
		<p>
			Allows to change default settings.
			If called without arguments, return an object containing name/value pairs reflecting the current settings
		</p>
	</div>
	<table class="table table-bordered luga-docs-api">
		<th colspan="3">Arguments</th>
		<tr>
			<td>options.rootPath</td>
			<td>
				{string}
			</td>
			<td>
				A base path that must be removed from the beginning of every url fragment.
				Default to empty string
			</td>
		</tr>
		<tr>
			<td>options.greedy</td>
			<td>
				{boolean}
			</td>
			<td>
				By default the Router execute the first RouteHandler that matches the url fragment.
				Set it to true to allow multiple routes matching. Default to false
			</td>
		</tr>
		<tr>
			<td>options.pushState</td>
			<td>
				{boolean}
			</td>
			<td>
				Set it to true if you want to list to window.popstate.
				Default to false and listen to window.hashchange instead.
				This is relevant only for client-side routing
			</td>
		</tr>
		<tr>
			<td>options.handlerConstructor</td>
			<td>
				{function}
			</td>
			<td>
				By default every time you call the .add() method, the Router create an instance of luga.router.RouteHandler.
				If you want to use a custom/different routeHandler class/constructor, use this setting.
				The given function must implement <a href="#extensibility/iroutehandler">IRouteHandler</a>
			</td>
		</tr>
	</table>
	<table class="table table-bordered luga-docs-api">
		<th>Examples</th>
	</table>

<pre><code class="language-javascript">var myRouter = new luga.router.Router();
myRouter.setup({
	rootPath: "",
	handlerConstructor: customHandlerConstructor
});
</code></pre>

</div>

<div class="panel panel-default">
	<div class="panel-heading luga-docs-api-heading">luga.Router.start()</div>
	<div class="panel-body">
		Stop the Router. If used client-side start listening to either the "hashchange" and "popstate" events.
		By default the Router listen to "hashchange", unless it's configured with pushState = true
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading luga-docs-api-heading">luga.Router.stop()</div>
	<div class="panel-body">
		Stop the Router. If used client-side stop listening to the "hashchange" and "popstate" events
	</div>
</div>